package workspace

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// settingsFor writes a workspace's settings and hands back the parsed JSON.
func settingsFor(t *testing.T, ws *Workspace) map[string]any {
	t.Helper()
	if err := os.MkdirAll(ws.MetaDir(), HomeDirMode); err != nil {
		t.Fatal(err)
	}
	if err := writeSettings(ws); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(ws.SettingsPath())
	if err != nil {
		t.Fatal(err)
	}
	var got map[string]any
	if err := json.Unmarshal(b, &got); err != nil {
		t.Fatal(err)
	}
	return got
}

func testWorkspace(t *testing.T) *Workspace {
	t.Helper()
	return &Workspace{ID: "ws", Dir: t.TempDir()}
}

// Loopback is not egress, and denying it costs whole packages: httptest
// binds an ephemeral 127.0.0.1/[::1] port and panics when refused, so
// internal/notify, internal/slack and internal/tracker could not be tested
// inside a sandbox at all.
func TestSandboxAllowsLoopbackBinds(t *testing.T) {
	got := settingsFor(t, testWorkspace(t))

	sandbox, _ := got["sandbox"].(map[string]any)
	network, _ := sandbox["network"].(map[string]any)
	if network["allowLocalBinding"] != true {
		t.Errorf("sandbox.network.allowLocalBinding = %v, want true; "+
			"without it every httptest-using package fails on bind, on every run",
			network["allowLocalBinding"])
	}
	// The allowlist is the thing loopback must not be confused with. It
	// governs egress and stays closed.
	if _, ok := network["allowedDomains"]; !ok {
		t.Error("allowedDomains disappeared; loopback is not a reason to open egress")
	}
}

// The agent must not have to invent its own cache location. It gets one in
// the environment, pointing somewhere the sandbox will actually let it
// write, or it redirects GOCACHE to a temp directory and recompiles the
// standard library once per ticket.
func TestBuildCacheIsProvisionedAndWritable(t *testing.T) {
	ws := testWorkspace(t)
	got := settingsFor(t, ws)
	cache := ws.BuildCacheDir()

	if fi, err := os.Stat(cache); err != nil || !fi.IsDir() {
		t.Fatalf("build cache %s was not created: %v", cache, err)
	}

	env, _ := got["env"].(map[string]any)
	if env["GOCACHE"] != cache {
		t.Errorf("env.GOCACHE = %v, want %s", env["GOCACHE"], cache)
	}

	// Naming it in the environment is only half of it: the OS sandbox denies
	// writes outside the permission scope, so a GOCACHE it does not know
	// about is a cache that fails on first write.
	perms, _ := got["permissions"].(map[string]any)
	dirs, _ := perms["additionalDirectories"].([]any)
	found := false
	for _, d := range dirs {
		if d == cache {
			found = true
		}
	}
	if !found {
		t.Errorf("permissions.additionalDirectories = %v, missing %s; "+
			"the sandbox would deny every write to the cache", dirs, cache)
	}
}

// "Survives between runs in the same sandbox" is the whole point. Settings
// are rewritten on every provision and re-bind, so rewriting them must not
// disturb what the last run compiled.
func TestBuildCacheSurvivesRewrittenSettings(t *testing.T) {
	ws := testWorkspace(t)
	settingsFor(t, ws)

	marker := filepath.Join(ws.BuildCacheDir(), "trim.txt")
	if err := os.WriteFile(marker, []byte("compiled"), 0o600); err != nil {
		t.Fatal(err)
	}

	settingsFor(t, ws) // a second `orion init`, or the next job
	if b, err := os.ReadFile(marker); err != nil || string(b) != "compiled" {
		t.Errorf("the cache was lost on rewrite (%v); every ticket would start cold", err)
	}
}

// A sandbox adopted before a policy fix must not keep the broken policy
// until someone thinks to re-run `orion init`. The run that would benefit is
// the one that cannot know it should.
func TestEveryJobRefreshesTheSandboxPolicy(t *testing.T) {
	ws := sandbox(t)
	if err := os.WriteFile(ws.SettingsPath(), []byte(`{"stale":true}`), PrivateFileMode); err != nil {
		t.Fatal(err)
	}

	if _, err := AddWorktree(ws, "develop", "orion/or-90"); err != nil {
		t.Fatal(err)
	}

	b, err := os.ReadFile(ws.SettingsPath())
	if err != nil {
		t.Fatal(err)
	}
	var got map[string]any
	if err := json.Unmarshal(b, &got); err != nil {
		t.Fatal(err)
	}
	if _, stale := got["stale"]; stale {
		t.Error("the job ran on settings generated by an older release")
	}
	sandboxCfg, _ := got["sandbox"].(map[string]any)
	network, _ := sandboxCfg["network"].(map[string]any)
	if network["allowLocalBinding"] != true {
		t.Error("the policy was not regenerated for this job")
	}
}

// `orion explore` has to be allowed outright. A supervised run is
// non-interactive, so a command that needs a permission prompt is a command
// that is denied -- and an explore that cannot run is an implementer grepping
// its way through the repository, which is the cost the whole thing removes
// (OR-183).
func TestSandboxAllowsTheExploreCommand(t *testing.T) {
	got := settingsFor(t, testWorkspace(t))

	perms, _ := got["permissions"].(map[string]any)
	allow, _ := perms["allow"].([]any)
	found := false
	for _, a := range allow {
		if s, ok := a.(string); ok && strings.Contains(s, "explore") {
			found = true
		}
	}
	if !found {
		t.Errorf("permissions.allow = %v, missing an explore rule; the subagent would be "+
			"unreachable from inside the run that is meant to use it", allow)
	}
}

// A cache under the repo directory would be rebuilt per ticket -- RepoDir
// resolves to the per-job worktree while a job runs -- and would dirty a
// clone that is fast-forwarded between runs.
func TestBuildCacheLivesOutsideTheRepo(t *testing.T) {
	ws := testWorkspace(t)
	job := &Workspace{ID: ws.ID, Dir: ws.Dir, RepoPath: filepath.Join(ws.Dir, "worktrees", "or-90")}

	for _, w := range []*Workspace{ws, job} {
		if strings.HasPrefix(w.BuildCacheDir(), w.RepoDir()+string(filepath.Separator)) {
			t.Errorf("build cache %s is inside the repo %s; it would not outlive the ticket",
				w.BuildCacheDir(), w.RepoDir())
		}
	}
	if ws.BuildCacheDir() != job.BuildCacheDir() {
		t.Errorf("per-job cache paths (%s vs %s); every ticket would compile from cold",
			ws.BuildCacheDir(), job.BuildCacheDir())
	}
}
